export type LegalAssistantInput = {
  jurisdiction: string
  scenario: 'sale' | 'lease' | 'agency' | 'developer'
  question: string
  propertySummary?: string
}

export function legalAssistant(input: LegalAssistantInput): {
  answer: string
  disclaimer: string
  references: { doc: string; section?: string }[]
  risks: string[]
} {
  const j = input.jurisdiction.trim() || 'your jurisdiction'

  const disclaimer =
    'This is general informational guidance generated by an assistant. It is not legal advice. Consult a qualified professional in your jurisdiction before acting.'

  const risks: string[] = []
  if (input.scenario === 'lease') risks.push('Tenant/landlord obligations vary by jurisdiction and contract terms.')
  if (input.scenario === 'sale') risks.push('Transfer terms (warranties, dates, conditions) must match local requirements.')
  if (input.scenario === 'agency') risks.push('Commission, exclusivity, and scope of mandate need clear written definitions.')
  if (input.scenario === 'developer') risks.push('Developer/fund contracts often involve regulatory disclosure and staged delivery terms.')

  const answerLines: string[] = []
  answerLines.push(`Jurisdiction: ${j}`)
  answerLines.push('')
  answerLines.push('Suggested approach (checklist):')
  answerLines.push('1. Confirm parties and roles (individual vs organization, mandates, authorizations).')
  answerLines.push('2. Match the contract type to your scenario.')
  answerLines.push('3. Verify key clauses: scope, timeline, payment terms, liabilities, termination, and dispute resolution.')
  answerLines.push('4. If there are property specifics, ensure they are reflected consistently (address, surface, condition, disclosures).')
  answerLines.push('')
  answerLines.push('Your question:')
  answerLines.push(input.question.trim() || '(not provided)')
  answerLines.push('')
  if (input.propertySummary) {
    answerLines.push('Property summary considered:');
    answerLines.push(input.propertySummary.trim())
    answerLines.push('')
  }
  answerLines.push(
    'Next step: tell me the country/city and whether this is a lease or a sale, and I will produce a structured list of clauses to ask your lawyer for.',
  )

  return {
    answer: answerLines.join('\n'),
    disclaimer,
    references: [{ doc: 'Default legal templates (placeholder)', section: input.scenario }],
    risks,
  }
}

