export type ThreeDJobInput = {
  listingId?: string
  kind: 'preview_from_plans' | 'convert_glb' | 'generate_thumbnail' | 'generic'
  payload?: Record<string, unknown>
}

export function buildThreeDJobOutput(job: ThreeDJobInput): {
  thumbnailUrl: string
  modelUrl?: string
  notes: string[]
} {
  return {
    // Public placeholder so the UI can show something immediately in the demo.
    thumbnailUrl:
      'https://images.unsplash.com/photo-1527030280862-64139fba04ca?w=1200&q=80',
    modelUrl: job.listingId ? `s3://your-bucket/converted_${job.listingId}.glb` : undefined,
    notes: [
      'Demo output generated by a stub.',
      'In production you will run your conversion/generation pipeline asynchronously.',
    ],
  }
}

